spring:
  application:
    name: USER-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-register: true
    service-url:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: https://service-registry-demo.herokuapp.com/eureka/
  instance:
    hostname: user-micro-service.herokuapp.com

